spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: system
    password: oracle
  jpa:
    database-platform: com.icthh.xm.commons.migration.db.jsonb.CustomOracleDialect
#    database-platform: org.hibernate.dialect.OracleDialect
    database: ORACLE
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.model.generator_name_as_sequence_name: false
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_minimal_puts: true
      hibernate.hbm2ddl.auto: none
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.interceptor: com.icthh.xm.commons.domainevent.db.service.DatabaseSourceInterceptor
      hibernate:
        dialect: com.icthh.xm.commons.migration.db.jsonb.CustomOracleDialect
