management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - health
          - info
          - jhimetrics
          - jhiopenapigroups
          - logfile
          - loggers
          - prometheus
          - threaddump
          - caches
          - metrics
          - liquibase
  endpoint:
    health:
      show-details: when_authorized
      roles: 'SUPER-ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
    jhimetrics:
      enabled: true
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  observations:
    key-values:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
  tracing:
    propagation:
      type: b3
    enabled: true
    sampling:
      probability: 1.0 # report 100% of traces

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      enabled: false
      discovery:
        instanceId: eir.management:${spring.application.instance-id:${random.value}}
        enabled: false
      config:
        enabled: false
    loadbalancer:
      enabled: false
  config:
    group:
      dev:
        - dev
        - api-docs
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.timezone.default_storage: NORMALIZE
      hibernate.type.preferred_instant_jdbc_type: TIMESTAMP
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_empty
    kafka:
      bootstrap-servers: localhost:9092
  messages:
    basename: i18n/messages
  mvc:
    problemdetails:
      enabled: true
  task:
    execution:
      thread-name-prefix: eir-management-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: eir-management-scheduling-
      pool:
        size: 2
  output:
    ansi:
      console-available: true
  application:
    name: eir-management

server:
  servlet:
    session:
      cookie:
        http-only: true

springdoc:
  show-actuator: true

xm-config:
  enabled: true
  xm-config-url: http://config
  kafka-config-topic: config_topic

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  clientApp:
    name: 'eirManagementApp'
  api-docs:
    default-include-pattern: ${server.servlet.context-path:}/api/**
    management-include-pattern: ${server.servlet.context-path:}/management/**
    title: EirManagement API
    description: EirManagement API documentation
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com data:"

application:
  specification-path-pattern: /config/tenants/{tenantName}/${spring.application.name}/example-of-microservice-spec.yml
  tenant-ignored-path-list: /v2/api-docs, /api/profile-info, /swagger-resources/configuration/ui, /management/health, /management/prometheus

  kafka-enabled: true
  scheduler-enabled: false

  kafka-system-topic: system_topic
  kafka-system-queue: system_queue
  kafka-metadata-max-age: 60000 #in milliseconds
  kafkaHealth:
    enabled: true
